
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v3.5  Build: December 11th, 2012
-- SQL Server 2000/2005/2008/2008R2/2012/Express DDL Script generated from project: NinjaSoftware.TrzisteNovca
-- Project filename: G:\Documents\Visual Studio 2010\Projects\NinjaSoftware.TrzisteNovca\NinjaSoftware.TrzisteNovca.llblgenproj
-- Script generated on: 20-ožu-2013 11:26.11
--
-- This is an Update script for updating an existing data model to a newer version. If you want DDL SQL for a new model,
-- please create a Create script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime.
--
-- Please run the scripts in the right order, use the timestamp in the filename and inside this script for that.
-- This script might need adjustment in some statements. You should consider this script as a starting point for
-- upgrading the existing data model.
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- Drop constraints referring to elements which are changed in this script (constraints are recreated later on)
-- ###############################################################################################################

USE [TrzisteNovca]
GO

ALTER TABLE [dbo].[Error] DROP CONSTRAINT [FK_ab4fe0247e582ce86e6abe92334]
GO

ALTER TABLE [dbo].[Error] DROP CONSTRAINT [PK_345c01a4dadaa2743b182e09867]
GO

-- ###############################################################################################################
-- Rename statements
-- ###############################################################################################################

USE [TrzisteNovca]
GO

-- ###############################################################################################################
-- DROP statements for elements no longer needed or replaced elements.
-- ###############################################################################################################

USE [TrzisteNovca]
GO

-- ###############################################################################################################
-- ADD statements for new elements (except FK/UC)
-- ###############################################################################################################

USE [TrzisteNovca]
GO

-- ###############################################################################################################
-- ALTER statements for table fields and ADD statements for new primary key constraints
-- ###############################################################################################################

USE [TrzisteNovca]
GO

ALTER TABLE [dbo].[Error] 
	-- Identity constraint was changed on field 'ErrorId'. However SQL Server doesn't allow changing this in SQL. 
	-- This means that you have to do this manually by creating a new temporary column, copy over all data and then remove 
	-- the column (cumbersome, due to FK constraints). Another, probably less cumbersome way, is to do this through SSMS, which 
	-- does the handling for you. Example of how to do it manually:
	-- http://stackoverflow.com/questions/702745/sql-server-how-to-drop-identity-from-a-column
	-- Discussion about this issue on MS' forums:
	-- http://social.msdn.microsoft.com/forums/en-US/transactsql/thread/04d69ee6-d4f5-4f8f-a115-d89f7bcbc032/
	ALTER COLUMN [ErrorId] [bigint] IDENTITY (1,1) NOT NULL
GO

ALTER TABLE [dbo].[Error] WITH NOCHECK 
	ADD CONSTRAINT [PK_345c01a4dadaa2743b182e09867] PRIMARY KEY CLUSTERED 
	( 
		[ErrorId] 
	) ON [PRIMARY]
GO

-- ###############################################################################################################
-- ADD statements for new foreign key constraints and unique constraints
-- ###############################################################################################################

USE [TrzisteNovca]
GO

ALTER TABLE [dbo].[Error] 
	ADD CONSTRAINT [FK_ab4fe0247e582ce86e6abe92334] FOREIGN KEY
	(
		[ParentErrorId] 
	)
	REFERENCES [dbo].[Error]
	(
		[ErrorId] 
	)
GO

