
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v3.5  Build: December 11th, 2012
-- SQL Server 2000/2005/2008/2008R2/2012/Express DDL Script generated from project: NinjaSoftware.TrzisteNovca
-- Project filename: G:\Documents\Visual Studio 2010\Projects\NinjaSoftware.TrzisteNovca\NinjaSoftware.TrzisteNovca.llblgenproj
-- Script generated on: 22-ožu-2013 14:49.34
--
-- This is an Update script for updating an existing data model to a newer version. If you want DDL SQL for a new model,
-- please create a Create script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime.
--
-- Please run the scripts in the right order, use the timestamp in the filename and inside this script for that.
-- This script might need adjustment in some statements. You should consider this script as a starting point for
-- upgrading the existing data model.
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- Drop constraints referring to elements which are changed in this script (constraints are recreated later on)
-- ###############################################################################################################

USE [TrzisteNovca]
GO

-- ###############################################################################################################
-- Rename statements
-- ###############################################################################################################

USE [TrzisteNovca]
GO

-- ###############################################################################################################
-- DROP statements for elements no longer needed or replaced elements.
-- ###############################################################################################################

USE [TrzisteNovca]
GO

-- ###############################################################################################################
-- ADD statements for new elements (except FK/UC)
-- ###############################################################################################################

USE [TrzisteNovca]
GO

CREATE TABLE [dbo].[RepoAukcija] 
(
	[BrojAukcije] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[DatumAukcije] [datetime] NOT NULL, 
	[DatumReotkupa] [datetime] NULL, 
	[FiksnaRepoStopa] [decimal] (5, 2) NULL, 
	[GranicnaRepoStopa] [decimal] (5, 2) NULL, 
	[KoeficijentRaspodjele] [decimal] (5, 2) NULL, 
	[NajnizaRepoStopa] [decimal] (5, 2) NULL, 
	[NajvisaRepoStopa] [decimal] (5, 2) NULL, 
	[OdbijenePonudeUkupno] [decimal] (10, 2) NULL, 
	[PostoPrihvacenihPoGranicnojStopi] [decimal] (5, 2) NULL, 
	[PrihvacenePonudeUkupno] [decimal] (10, 2) NULL, 
	[PristiglePonudeUkupno] [decimal] (10, 2) NULL, 
	[RepoAukcijaId] [bigint] IDENTITY (1,1) NOT NULL, 
	[VaganaRepoStopa] [decimal] (5, 2) NULL 
) ON [PRIMARY]
GO

-- ###############################################################################################################
-- ALTER statements for table fields and ADD statements for new primary key constraints
-- ###############################################################################################################

USE [TrzisteNovca]
GO

ALTER TABLE [dbo].[RepoAukcija] WITH NOCHECK 
	ADD CONSTRAINT [PK_98fd1e245f4ac2cb3381fe9ef20] PRIMARY KEY CLUSTERED 
	( 
		[RepoAukcijaId] 
	) ON [PRIMARY]
GO

-- ###############################################################################################################
-- ADD statements for new foreign key constraints and unique constraints
-- ###############################################################################################################

USE [TrzisteNovca]
GO

