
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v3.5  Build: December 11th, 2012
-- SQL Server 2000/2005/2008/2008R2/2012/Express DDL Script generated from project: NinjaSoftware.TrzisteNovca
-- Project filename: G:\Documents\Visual Studio 2010\Projects\NinjaSoftware.TrzisteNovca\NinjaSoftware.TrzisteNovca.llblgenproj
-- Script generated on: 31-ožu-2013 10:37.24
--
-- This is an Update script for updating an existing data model to a newer version. If you want DDL SQL for a new model,
-- please create a Create script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime.
--
-- Please run the scripts in the right order, use the timestamp in the filename and inside this script for that.
-- This script might need adjustment in some statements. You should consider this script as a starting point for
-- upgrading the existing data model.
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- Drop constraints referring to elements which are changed in this script (constraints are recreated later on)
-- ###############################################################################################################

USE [atjanmcs301107hr2706_tn]
GO

-- ###############################################################################################################
-- Rename statements
-- ###############################################################################################################

USE [atjanmcs301107hr2706_tn]
GO

-- ###############################################################################################################
-- DROP statements for elements no longer needed or replaced elements.
-- ###############################################################################################################

USE [atjanmcs301107hr2706_tn]
GO

-- ###############################################################################################################
-- ADD statements for new elements (except FK/UC)
-- ###############################################################################################################

USE [atjanmcs301107hr2706_tn]
GO

CREATE TABLE [dbo].[TrgovanjeGlavaHnb] 
(
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Datum] [datetime] NOT NULL, 
	[TrgovanjeGlavaHnbId] [bigint] IDENTITY (1,1) NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TrgovanjeStavkaHnb] 
(
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[IznosMilijuniKn] [decimal] (10, 2) NULL, 
	[KamatnaStopa] [decimal] (6, 2) NULL, 
	[TrgovanjeGlavaHnbId] [bigint] NOT NULL, 
	[TrgovanjeStavkaHnbId] [bigint] IDENTITY (1,1) NOT NULL, 
	[TrgovanjeVrstaId] [bigint] NOT NULL 
) ON [PRIMARY]
GO

-- ###############################################################################################################
-- ALTER statements for table fields and ADD statements for new primary key constraints
-- ###############################################################################################################

USE [atjanmcs301107hr2706_tn]
GO

ALTER TABLE [dbo].[TrgovanjeGlavaHnb] WITH NOCHECK 
	ADD CONSTRAINT [PK_b7551c04a4bb25446764e1fd434] PRIMARY KEY CLUSTERED 
	( 
		[TrgovanjeGlavaHnbId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TrgovanjeStavkaHnb] WITH NOCHECK 
	ADD CONSTRAINT [PK_964d2cd4de99af6cd17e1c40f50] PRIMARY KEY CLUSTERED 
	( 
		[TrgovanjeStavkaHnbId] 
	) ON [PRIMARY]
GO

-- ###############################################################################################################
-- ADD statements for new foreign key constraints and unique constraints
-- ###############################################################################################################

USE [atjanmcs301107hr2706_tn]
GO

ALTER TABLE [dbo].[TrgovanjeStavkaHnb] 
	ADD CONSTRAINT [FK_fc65ac84afc842c617e89b47646] FOREIGN KEY
	(
		[TrgovanjeVrstaId] 
	)
	REFERENCES [dbo].[TrgovanjeVrstaRo]
	(
		[TrgovanjeVrstaId] 
	)
GO

ALTER TABLE [dbo].[TrgovanjeStavkaHnb] 
	ADD CONSTRAINT [FK_31f714f4d9b981f0935f11920c9] FOREIGN KEY
	(
		[TrgovanjeGlavaHnbId] 
	)
	REFERENCES [dbo].[TrgovanjeGlavaHnb]
	(
		[TrgovanjeGlavaHnbId] 
	)
GO

